export { default as LandingPage } from './LandingPage';
export { default as TermsPage } from './TermsPage';
export { default as PrivacyPage } from './PrivacyPage';
export { default as FAQPage } from './FAQPage';
export { default as ContactPage } from './ContactPage';
export { default as LoginPage } from './LoginPage';
export { default as RegisterPage } from './RegisterPage';
export { default as OnboardingPage } from './OnboardingPage';
export { default as SettingsPage } from './SettingsPage';
